server:
  port: 7001
spring:
  rabbitmq:
    host: 118.25.35.116
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 60000 #毫秒
    publisher-confirms: true #消息确认
    publisher-returns: true
    cache:
      channel:
        size: 2
logging:
  level:
    root: debug

